[package]
name = "deno_os"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
path = "lib.rs"

[dependencies]
rquickjs = { version = "=0.11.0", features = ["classes", "properties", "loader"] }
serde_json = { version = "1.0.148" }
sui_kai = { path = "../../crates/sui_kai" }
utils = { path = "../utils" }
utils_macros = { path = "../utils/macros" }

[lints]
workspace = true
