# SPDX-License-Identifier: Apache-2.0 OR MIT
# https://github.com/taiki-e/setup-cross-toolchain-action

name: Setup musl toolchain
description: Install musl toolchain with C++ support for cross-compilation
inputs:
  target:
    description: Target triple (e.g., x86_64-unknown-linux-musl)
    required: true

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build musl toolchain image
      uses: docker/build-push-action@v6
      with:
        context: ${{ github.action_path }}/../../docker/musl-toolchain
        build-args: |
          RUST_TARGET=${{ inputs.target }}
          UBUNTU_VERSION=24.04
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
        tags: musl-toolchain:latest

    - name: Extract and install toolchain
      shell: bash
      env:
        INPUT_TARGET: ${{ inputs.target }}
      run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
