name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  ci:
    name: Format & Lint
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: denoland/setup-deno@v2
        with:
          cache: true
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: deno task check:format
      - name: Check Lint
        run: deno task lint
      - name: Check types
        run: deno check --unstable-tsgo

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    permissions: {}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
          - os: macos-15-intel
            target: x86_64-apple-darwin
          - os: macos-15
            target: aarch64-apple-darwin
          - os: windows-2025
            target: x86_64-pc-windows-msvc
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Setup mold
        uses: rui314/setup-mold@v1
      - uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Setup cross-compilation toolchain
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - name: Build
        run: deno task build --target ${{ matrix.target }}
      - name: Test
        run: deno task test --target ${{ matrix.target }}

      - name: Collect binary sizes
        run: |
          mkdir -p sizes
          deno task check:size ${{ matrix.target }} > sizes/${{ matrix.target }}.json
          cat sizes/${{ matrix.target }}.json

      - name: Upload binary size info
        uses: actions/upload-artifact@v5
        with:
          name: binary-sizes-${{ matrix.target }}
          path: sizes/
          retention-days: 1

  save-pr-number:
    name: Save PR Number
    runs-on: ubuntu-latest
    permissions: {}
    if: github.event_name == 'pull_request'
    steps:
      - name: Save PR number
        run: |
          mkdir -p pr-number
          echo ${{ github.event.number }} > pr-number/pr_number
      - uses: actions/upload-artifact@v6
        with:
          name: pr-number
          path: pr-number/
          retention-days: 1
